### ISSUE TITLE
The Ministry of Bending Reality and Michael Stephens

### ISSUE THREAD

**Issue by BendingRealityTV** [ARRRmada/ARRRmada.com#17]
### Submission Type

New listing

### Merchant Listing Code

JTVCJTIyY2lsN0hjdFAlMjIlMkMlMjJUaGUlMjBNaW5pc3RyeSUyMG9mJTIwQmVuZGluZyUyMFJlYWxpdHklMjIlMkMlMjJUaGUlMjBNaW5pc3RyeSUyMG9mJTIwQmVuZGluZyUyMFJlYWxpdHklMjBmb2xsb3dzJTIwQnVzaW5lc3MlMjBEZXZlbG9wZXIlMkMlMjBBY3RpdmlzdCUyQyUyMEF1dGhvciUyQyUyMEludHVpdGl2ZSUyMENvbnN1bHRhbnQlRTIlODQlQTIlMkMlMjBIaXN0b3JpYW4lMjBhbmQlMjBOYW1lJTIwUmVhZGVyJUUyJTg0JUEyJTIwTWljaGFlbCUyMFN0ZXBoZW5zLiUyMiUyQyUyMkJlbmRpbmctUmVhbGl0eS1Mb2dvLTMoMTM1VykuanBnJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ3d3cuYmVuZGluZ3JlYWxpdHkuaXMlMkYlMjIlMkMlNUIlMjIzJTIyJTJDJTIyNyUyMiUyQyUyMjU2JTIyJTJDJTIyMTYlMjIlMkMlMjIyNyUyMiU1RCU1RA==

### Merchant Listing Image

![Bending-Reality-Logo-3(135W)](https://github.com/ARRRmada/ARRRmada.com/assets/150097411/3155e104-f0d7-40d2-a466-9a9999ab4a41)

### Comments for listing reviewer (optional)

Thank you!

**Comment by scott-ftf** [comment]
Hello @BendingRealityTV thanks for submitting your application. We will review shortly.

I took only a quick look, and I did not see ARRR was accepted on your website, but to be honest I couldn't find a cart or products. Could you provide a link to what services or products you offer and where users pay?

**Comment by zseko** [comment]
> Hello @BendingRealityTV thanks for submitting your application. We will review shortly.
> 
> I took only a quick look, and I did not see ARRR was accepted on your website, but to be honest I couldn't find a cart or products. Could you provide a link to what services or products you offer and where users pay?

He is using the donation button:
https://bendingreality.is/DONATE/

**Comment by zseko** [comment]
Ahoy @BendingRealityTV!

Welcome to the fleet of the ARRRmada.

If you have any questions or suggestions, you can find us in the official Discord.

https://twitter.com/PirateARRRmada/status/1721970892685680727
https://discord.com/channels/512188534111862784/836330876312354836/1171529687994990752

Best RegARRRds

**Comment by scott-ftf** [comment]
Welcome to ARRRmada @BendingRealityTV! Thanks for listing your website
