### ISSUE TITLE
New Listing for Xed’s Wonderland Emporium, LLC

### ISSUE THREAD

**Issue by MaxZero101** [ARRRmada/ARRRmada.com#19]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyVTZyb0lrbG4lMjIlMkMlMjJYZWQlRTIlODAlOTlzJTIwV29uZGVybGFuZCUyMEVtcG9yaXVtJTJDJTIwTExDJTIyJTJDJTIyU2VsbGluZyUyMHQtc2hpcnRzJTJDJTIwbWFnbmV0cyUyQyUyMHN0aWNrZXJzJTJDJTIwJTI2YW1wJTNCJTIwbW9yZSElMjBBYmxlJTIwdG8lMjBkbyUyMGN1c3RvbSUyMGRlc2lnbnMlMjBmb3IlMjBwcmludGluZy4lMjBBbHNvJTIwc2VsbGluZyUyMGhhbmRjcmFmdGVkJTIwc29hcHMlMjBhbmQlMjBsaXAlMjBiYWxtcy4lMjBMZXQlMjB1cyUyMGtub3clMjB5b3VyJTIwbmVlZHMhJTIyJTJDJTIySU1HXzA5OTEuanBlZyUyMiUyQyUyMmh0dHBzJTNBJTJGJTJGd3d3LnhlZHNlbXBvcml1bS5jb20lMjIlMkMlNUIlMjI0JTIyJTJDJTIyOSUyMiUyQyUyMjU2JTIyJTJDJTIyMjYlMjIlMkMlMjIyOCUyMiUyQyUyMjMxJTIyJTVEJTVE
---END CODE---

### Merchant Listing Image

![IMG_0991](https://github.com/ARRRmada/ARRRmada.com/assets/74627989/c4cd42c5-f3ad-4e72-8c18-98a1a36032ae)

**Comment by zseko** [comment]
Ahoy @MaxZero101,

thank you for submitting your listing entry! We are currently checking your entry and ask for your patience.

If you need help to receive ARRR via a payment gateway, we recommend CryptoCurrencycheckout, which allows you to receive BTC, USDT and many other coins/tokens in addition to ARRR.

https://cryptocurrencycheckout.com

Best RegARRRds

**Comment by zseko** [comment]
Ahoy @MaxZero101 

Welcome to the ARRRmada fleet. ⚓️

We recommend https://cryptocurrencycheckout.com for accepting $ARRR. Very easy to implement and supports many other coins besides ARRR.

https://twitter.com/PirateARRRmada/status/1722712764047597718
https://discord.com/channels/512188534111862784/836330876312354836/1172271568425078844

For further questions don't hesitate to contact us.

Best RegARRRds 🏴‍☠️

**Comment by zseko** [comment]
Ahoy @MaxZero101 

Welcome to the ARRRmada fleet. ⚓️

We recommend https://cryptocurrencycheckout.com for accepting $ARRR. Very easy to implement and supports many other coins besides ARRR.

https://twitter.com/PirateARRRmada/status/1722712764047597718
https://discord.com/channels/512188534111862784/836330876312354836/1172271568425078844

For further questions don't hesitate to contact us.

Best RegARRRds 🏴‍☠️
