### ISSUE TITLE
A-Computer Service (ACS)

### ISSUE THREAD

**Issue by arrrtto** [ARRRmada/ARRRmada.com#21]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIySjZWNzJuaUslMjIlMkMlMjJBLUNvbXB1dGVyJTIwU2VydmljZSUyMChBQ1MpJTIyJTJDJTIySVQlMjAlMjZhbXAlM0IlMjBBdWRpbyUyNiUyM3gyRiUzQlZpZGVvJTIwc2VydmljZXMuJTIwQWxsJTIwZGV0YWlsZWQlMjBpbmZvJTIwaXMlMjBvbiUyMHRoZSUyMHdlYnNpdGUuJTIyJTJDJTIyQUNTXzIwMjMucmVzaXplZC5wbmclMjIlMkMlMjJodHRwcyUzQSUyRiUyRnFvcnRhbC5saW5rJTJGQUNTJTJGRU4lMjIlMkMlNUIlMjI1NyUyMiUyQyUyMjU2JTIyJTJDJTIyMTIlMjIlMkMlMjIxNiUyMiUyQyUyMjQ0JTIyJTJDJTIyNDclMjIlNUQlNUQ=
---END CODE---

### Merchant Listing Image

![ACS_2023 resized](https://github.com/ARRRmada/ARRRmada.com/assets/147250571/24433f7f-727c-43b7-b8ee-d3bb6a7a8563)

**Comment by zseko** [comment]
Ahoy Artto,

thank you for being on board. ⚓️

Your listing has been approved and shared on the following platforms.

https://twitter.com/PirateARRRmada/status/1723984363078001010
https://discord.com/channels/512188534111862784/836330876312354836/1173543222602125352

Best RegARRRds 🏴‍☠️

**Comment by scott-ftf** [comment]
Welcome to arrrmada @arrrtto!
