### ISSUE TITLE
What The Finance

### ISSUE THREAD

**Issue by DreamTrims** [ARRRmada/ARRRmada.com#25]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyc21ZSHNCZE0lMjIlMkMlMjJXaGF0JTIwVGhlJTIwRmluYW5jZSUyMiUyQyUyMlJlYWQlMjB3aGF0JTIwb3RoZXJzJTIwd29uJTI2JTIzMDM5JTNCdCUyMHRlbGwlMjB5b3UuJTIwSW5kZXBlbmRlbnQlMjBqb3VybmFsaXNtJTIwZm9yJTIwZGVjZW50cmFsaXplZCUyMGFuZCUyMHRyYWRpdGlvbmFsJTIwZmluYW5jZSUyMHNpbmNlJTIwMjAwOC4lMjIlMkMlMjJ3dGYtbG9nby12Mi13aGl0ZS5wbmclMjIlMkMlMjJodHRwcyUzQSUyRiUyRndoYXR0aGVmaW5hbmNlLmNvbSUyRiUyMiUyQyU1QiUyMjclMjIlNUQlNUQ=
---END CODE---

### Merchant Listing Image

![wtf-logo-v2-white](https://github.com/ARRRmada/ARRRmada.com/assets/62569559/e7fb5558-0fbd-4826-8dec-9e0447558765)
![wtf-logo-v2](https://github.com/ARRRmada/ARRRmada.com/assets/62569559/31be4a06-f032-4ce2-95d0-b5704b2d450f)

**Comment by zseko** [comment]
Ahoy @DreamTrims, thanks for submitting your listing. We ARRR reviewing your submtting now.

**Comment by zseko** [comment]
Ahoy mate,

thank you for being on board. ⚓️

Your listing has been approved and shared on the following platforms.

https://twitter.com/PirateARRRmada/status/1725046974792061018
https://discord.com/channels/512188534111862784/836330876312354836/1174605802003238922
https://t.me/c/1452389363/3562

Best RegARRRds 🏴‍☠️
