### ISSUE TITLE
Unicorn Horn PMA

### ISSUE THREAD

**Issue by pbrooksmc** [ARRRmada/ARRRmada.com#28]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyUXFPU212MjklMjIlMkMlMjJVbmljb3JuJTIwSG9ybiUyMFBNQSUyMiUyQyUyMk1ha2luZyUyMHRoZSUyMEZpbmVzdCUyMEhvbGlzdGljJTIwSGVhbHRoJTIwUHJvZHVjdHMlMkMlMjBDYW5kbGVzJTJDJTIwV2FzaGVzJTIwYW5kJTIwT2lscyUyMG9uJTIwdGhlJTIwTWFya2V0JTIyJTJDJTIyQnJvb2tzJTIwRUhhcm1vbnklMjAxMC0yMC0xMy5KUEclMjIlMkMlMjJodHRwcyUzQSUyRiUyRmRhd25pbmdzYXJ0LmNvbSUyMiUyQyU1QiUyMjEyJTIyJTJDJTIyMjAlMjIlMkMlMjIyNCUyMiUyQyUyMjI3JTIyJTJDJTIyMzUlMjIlMkMlMjIzOSUyMiU1RCU1RA==
---END CODE---

### Merchant Listing Image

![Group-6 edit](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/9b9a5f26-86be-4f80-9945-67e4af74752f)

### Comments for listing reviewer (optional)

Our New Product is Calendula Lavender Skin Balm. Put on any Skin Problem, use for skin moisturizing and beauty reasons. Has worked on everything we have used it for to date.

**Comment by pbrooksmc** [comment]
We accept Pirate Chain Coins.  ARRR Matey

**Comment by pbrooksmc** [comment]
![Standard Herb Oil 1 002](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/841de969-b100-4267-a417-60e322d49e03)

**Comment by pbrooksmc** [comment]
[Wholesale Oils and Wash List - each.odt](https://github.com/ARRRmada/ARRRmada.com/files/13881317/Wholesale.Oils.and.Wash.List.-.each.odt)

**Comment by pbrooksmc** [comment]
[Wholesale Oils and Wash List - each.odt](https://github.com/ARRRmada/ARRRmada.com/files/13881319/Wholesale.Oils.and.Wash.List.-.each.odt)

**Comment by pbrooksmc** [comment]
[Ear Candle Wholesale Price List-each.odt](https://github.com/ARRRmada/ARRRmada.com/files/13881322/Ear.Candle.Wholesale.Price.List-each.odt)

**Comment by pbrooksmc** [comment]
![River Flowers May 28, 2020 008](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/8c2d1d14-31f6-4348-b1a4-481fd433d4bd)
![Uploading River Flowers May 28, 2020 012.JPG…]()

**Comment by pbrooksmc** [comment]
![778c1c23c8030f32fb270a39a8c16917](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/d4916ce4-a3d0-420d-8e51-9218e393bb98)

**Comment by pbrooksmc** [comment]
OILS & WASH LIST
We accept United States Currency & Bitcoin “BTC” upon receipt. You receive 2.5% off total order for paying in:  Monaro “XMR”.  You receive 10% off total order for paying in: Pirate Chain “ARRR”, Wownero “WOW”, Iridium “IRD”, Oxen “OXEN”, RYO Currency “RYO”. Contact us to agree on payment details.
Free Shipping on 6 cases, mix and match.  $10.20 shipping on 5-2oz bottles & 7-1-oz bottles.
Unicorn Horn "Standard Herb" Oil
One-ounce amber glass bottles with dropper. Antiseptic, antifungal, anti-itch, slightly anti-bacterial. Excellent for earaches, this oil is formulated to be used in the ear. It is our number one choice for most earaches. This is our best all-around herb oil. Use on most any skin problem. Good on burns, scalds, scrapes and chigger bites. It is great when used on the skin for bug bites, will stop mosquito bites from itching, will soothe any bug bite or sting and is an effective bug repellent. No camping trip should be without this oil. Can be useful on poison oak and ivy.
Ingredients: Calendula Flower, Garlic Bulb, Saint Johnswort, Vitamin E Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL
1 oz.  $9.50
2 oz. $18.00
4 oz. $35.00
Wholesale
1oz amber glass bottle
$4.75 each
2oz amber glass bottle
$9.00 each
4oz amber glass bottle
$17.50 each
Unicorn Horn "Garden Delight" Ear Oil
(Post Ear Candling Oil)
One-ounce amber glass bottles with dropper. Soothes and heals an earache. A wonderfully mild healing oil. Can be used on children. This oil is a very good earwax softener. We recommend this as our post candling oil for all types of ear candles. This oil dissolves beeswax residue, which makes it the perfect post ear candling oil. Can be used on the scalp. Is a very good hand lotion. Smells good. Is a deep cleaning oil. Recommended for maintenance oiling of the ears between candlings.
Ingredients: Ginger Oil, Myrrh Oil, Celery Seed Oil, Carrot Seed Oil, Vitamin E Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
1 oz.  $ 8.00
2 oz. $15.00
4 oz. $29..00
Wholesale
1oz amber glass bottle
$4.00 each
2oz amber glass bottle
$7.50 each
4oz amber glass bottle
$14.50 each
Unicorn Horn "Garlic" Ear Oil
One-ounce amber glass bottles with dropper. Antiseptic, slightly anti-bacterial. Can relieve earache. This oil is formulated to be used in the ear. Can be used on children. Good for itching of the ear. Helpful for warts, diaper rash, infection, ringworm, and yeast infections.
Ingredients: Garlic Bulb, Vitamin E Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
1 oz. $ 7.50
2 oz. $ 14.50
4 oz. $28.00
1oz amber glass bottle
$3.75 each 
2oz amber glass bottle
$7.25 each 
4oz amber glass bottle
$14.00 each 
Unicorn Horn "Malelueca Bazooka" Ear Oil
One-ounce amber glass bottles with dropper. Antifungal, antiseptic. This is our best earwax softener. It will virtually dewax your ear and will treat most fungus conditions. Best results for fungus is if used in conjunction with Unicorn Horn Candida Vambeata Ear Wash. Fungus can cause itching of the ear and some ringing. This oil lives up to its name. Use this oil for earaches and infections. Superb on sunburns, good on any burn. Good on athlete's foot. Excellent pre-candling oil. Use on bug bites and skin irritations. Good for ingrown toenails.
Ingredients: Malelueca (Tea Tree) Oil, Vitamin E Oil, Sage Oil, Clove Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
1 oz.  $12.00
2 oz. $23.00
4 oz. $45.00
1oz
$6.00 each
2oz
$11.50 each
4oz
$22.50 each
Unicorn Horn Oregon "Wild Lavender Flower" Ear Oil
One-ounce amber glass bottles with dropper. This is a very cleansing and healing ear oil.
Ingredients: Vitamin E Oil, Lavender Flower, Ginger, Myrrh
Base: Sunflower Seed Oil, Grape Seed Oil
SUGGESTED RETAIL:
1 oz.  $9.50
2 oz. $18.00
4 oz. $35.00
1oz
$4.75 each
2oz
$9.00 each
4oz
$17.50 each

Unicorn Horn "Penny Royal" Ear Oil
One-ounce amber glass bottles with dropper. Designed for sinus and allergy problems. Can relieve earache. This oil is formulated to be used in the ear.
Ingredients: Penny Royal, Saint Johnswort, Vitamin E Oil, Grape Seed Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
1 oz.  $ 12.00
2 oz. $23.50 
4 oz. $45.00
1oz
$6.00 each 
2oz
$11.75 each
4oz
$22.50 each



Unicorn Horn "Golden Myrrh" Ear Oil
One-ounce amber glass bottles with dropper. A very healing oil. A good beauty aid. Use with the Bayberry Golden Myrrh ear candles.
Ingredients: Myrrh Oil, Marijoram, Vitamin E Oil, Sunflower Seed Oil, Grape Seed Oil Base
SUGGESTED RETAIL:
1 oz. $12.50 
2 oz. $24.50 
4 oz. $48.00 
1oz
$6,25 each
2oz
$12.25 each          
4oz
$24.00 each


Unicorn Horn "Standard Wax Gone" Ear Dewaxer
One-ounce amber glass bottles with dropper. This unique combination dissolves and softens earwax. If earwax is the problem, this is an answer that works safely and well. This is a pleasant way to dewax your ears. The vitamin E is mixed in as a major ingredient so that your ear canal is conditioned and soothed. The herbs Penny Royal (airy), Myrrh (healing) and Tea Tree (wax cutter), are wonderful for the ear canal. This is a super moisturizing formula, a must for people who take frequent showers or swim. If itching of the ear canal is a problem this formula could help (one cause of itching is the need for moisturizing, another is for old, dry wax). It is an emulsion, so shake very well before using.
Ingredients: Tea Tree Oil, Vitamin E Oil
 Base: Light Density Liquid Petrolatum, Hydrogen Peroxide (anti-infective) H2O2, Witch Hazel
SUGGESTED RETAIL:
1 oz. $10.50
2 oz. $20.50
4 oz. $40.25
1oz
$5.25  each
2oz
$10.25 each 
4oz
$20.125  each

Unicorn Horn "Herbal Magic" Ear Wash
Two-ounce amber glass bottles with dropper. Anti-bacterial, antiseptic, anti-infective. Excellent ear wash. Kills germs and disinfects. If used after a swim, prevents swimmers ear. Use for bedsores, diaper rash, scrapes or cuts, swimmers ear, mouth gargle and wash (do not swallow), or poor circulation.
Ingredients: Witch Hazel, Southern Wood, Horehound Extract, Chamomile, Calendula, Penny Royal, Saint Johnswort, Sage, Tea Tree, Hydrogen Peroxide (50% by volume), 1.3% Anti-Infective H2O2 Base
SUGGESTED RETAIL:
2 oz. $ 12.50
4 oz. $24.50
8 oz. $48.50
2oz
$6.25   each
4oz
$12.25 each
8oz
$24.25 each


Unicorn Horn "Candida Vambeata" Ear Wash
(Anti-Fungicide Wash)
Two-ounce amber glass bottles with dropper. Anti-fungicide, antiseptic, anti-infective. Excellent anti-fungicide ear wash. Kills fungus, kills germs and disinfects. Excellent to use for and will cure Candida Albicans. Use for any fungus infestation of the ear. Use on feet and other places where fungus can grow. Will treat most fungus conditions. Best results if used in conjunction with Unicorn Horn Malelueca Bazooka Ear Oil and Tea Tree Gold Ear Candles. Fungus can cause itching of the ear and some ringing.
Ingredients: Tea Tree Oil, Calendula, Penny Royal, Saint Johnswort, Chamomile, Sage
Base: White Vinegar, Isopropyl Alcohol, Witch Hazel, H2O2 Hydrogen Peroxide
SUGGESTED RETAIL: 
2 oz. $ 12.00
4 oz. $23.50
8 oz. $34.50
2oz
$6.00  each
4oz
$11.75 each
8oz
$17.25 each


BODY & MASSAGE OILS & HEALERS
Unicorn Horn "Healing Power" Body Oil
Two-ounce amber glass bottles with dropper. Anti-fungal, anti-bacterial, antiseptic, anti-itch. Healing Power Body Oil is a powerfully potent, healing herb formulation. Use on skin problems. Heals and soothes most skin disorders including burns, thrush, impetigo, chilblains and athlete's foot. A remedy for ulcerated conditions such as varicose veins. Provides relief from eruptive skin diseases such as shingles (herpes zoster). Use as a massage oil on sore tendons and muscles, or varicose veins. Best results with hot towels. Great on bug bites and stings and is an exceptional bug repellent. Will kill mosquitoes.
Ingredients: Calendula Flower, Garlic Bulb, Saint Johnswort, Vitamin E Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
2 oz. $25.00
4 oz. $49.50 
8 oz. $98.00
2oz
$12.50 each
4oz
$24.75 each
8oz
$49.00 each
Unicorn Horn "Sun Burn Healer"
Two-ounce amber glass bottles with dropper. Anti-fungal, antiseptic. A very potent formula. Excellent for sunburns, use on any burn. WILL STOP SUNBURN PAIN. Will start healing the burned skin immediately and will retard peeling and blistering. This is a wonderful natural formula that works better than any product we have seen for sunburns. It is very nourishing for the skin. For best anti-blistering results Sun Burn Healer should be applied immediately after being sun burnt and should be used liberally several times per day. Great for ingrown toenails. Use on skin problems. Use on sunburns and skin problems. It is a very healing massage oil.
Ingredients: Malelueca (Tea Tree) Oil, Vitamin E Oil, Sage Oil, Clove Oil, Sunflower Seed Oil Base
SUGGESTED RETAIL:
2 oz. $30.00
4 oz. $59.00
8 oz. $117.00
2oz
$15.00 each
4oz
$29.50 each
8oz
$58.50 each


Unicorn Horn "Standard Massage" Oil
Four-ounce amber glass bottles. Soothes and relaxes. Has a wonderful herbiness scent. The texture of the oil is velvety and buttery. It goes a long way compared to a rapeseed oil and other massage oils of a similar quality. The skin likes this oil and leaves behind a nice surface, moisturized, not greasy. Many users say that their skin feels nourished after using. People with dry skin often feel cool and tingly and may really appreciate this oil's special moisturizing qualities.
Ingredients: Camphor, Eucalyptus, Marijarom Wild, Wintergreen, Clove, Vitamin E Oil, Sunflower Seed Oil, Grape Seed Oil Base
SUGGESTED RETAIL:
4 oz. $30.50
4oz. $15.25 each
Unicorn Horn "Wound Healer"
(Topical Wound and Cut Tonic)
Two-ounce amber glass bottles with dropper. Anti-bacterial, antiseptic, anti-infective. Kills germs and disinfects. This should be an essential item for every home medicine cabinet. Use topically for wounds and cuts, hemorrhage, inflammation, scrapes, nosebleed, bruises, mucous membranes, insect bites, hemorrhoids, stings, minor burns, poison ivy, sinus congestion, eases varicose veins. If you have a cut or scrape, this is an essentially painless preparation that works better than any over-the-counter preparation except iodine (iodine is not essentially painless). Can be used as a mouthwash for bleeding gums and after tooth extractions. As a gargle for sore throat. Splashed on the face, it is a revitalizing skin tonic that helps eliminate excess oil (keep out of the eyes). An excellent pimple wash. Works great on cold and canker sores.
Ingredients: Tea Tree, Penny Royal
Base: Snapping Hazel, Hydrogen Peroxide, 1.3% Anti-Infective H2O2      
SUGGESTED RETAIL:
2 oz. $ 16.00 
4 oz. $31.50
8 oz.$62.00
2oz
$8.00 each
4oz
$15.75 each
8oz
$31.00 each

Unicorn Horn "Wild Lavender" Massage Oil
Four-ounce amber glass bottles. Soothes, deep-cleans and revitalizes. Very good massage oil. Has special healing qualities. The skin likes this oil. Smells good.
Ingredients: Vitamin E Oil, Wild Lavender Flower, Ginger, Myrrh
Base: Sunflower Seed Oil, Grape Seed Oil, Avocado Oil, Jojoba Oil, Olive Oil
SUGGESTED RETAIL:
4 oz. $ 30.00 
8 oz. $59.50 
4oz
$15.00

8oz
$29.50 

PETS

HERBAL MAGIC HERB OIL — Works good on dog’s ears. Use topically on dog and cat skin problems. This is a very good healing oil.
WOUND HEALER — Works well on any animal.
GARDEN DELIGHT EAR OIL — Works well on cat ears.
HERBAL MAGIC EAR WASH — Works good on dog and car ear infections. Is a superb wound disinfectant. Should be used in combination with the above oils. This should be in every pet owner's medicine cabinet.
Unicorn Horn "Purr-Fect" Mite Oil For Cats
One-ounce amber glass bottles with dropper. A good natural remedy for cat ear mites.
Ingredients: Vitamin E Oil, Myrrh Oil, Marijoram Wild, Celery Seed Oil, Mineral Oil Base
SUGGESTED RETAIL:
1oz. $30.00 
2 oz. $59.50
1oz
$15.00 each

2oz
$29.25 each

**Comment by pbrooksmc** [comment]
Unicorn Horn Inc.
P.O. Box 2501
Gearhart, Oregon 97138
503-975-9540
A case of Ear Candles is 26 sets
We accept United States Currency & Bitcoin “BTC” upon receipt. You receive 2.5% off total order for paying in:  Monaro “XMR”.  You receive 10% off total order for paying in: Pirate Chain “ARRR”, Wownero “WOW”, Iridium “IRD”, Oxen “OXEN”, RYO Currency “RYO”. Contact us to agree on payment details.
Ear Candle Price List
We allow mixing of the cases for Free Shipping. Order any 6 cases mix & receive FREE SHIPPING
26 sets are in a case. Minimum order is 6 sets. Each set includes two ear candles & 25 step instructions.

Unicorn Horn "Standard" Blue Ear Candles				 Retail $8.50
These are our most popular and best selling ear candles. They come in the blue package. Use Standard Herb Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% bleached washed
Waxes: 90% candle wax, 10% beeswax
Herbs: Calendula Flower, Garlic Bulb, Saint Johnswort, Vitamin E Oil
$4.25 each 

Unicorn Horn "Standard" Tan Ear Candles				Retail $8.25
Made with unbleached cotton. They come in the tan package. Use Standard Herb Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% unbleached washed muslin
Waxes: 90% candle wax, 10% beeswax
Herbs: Calendula Flower, Garlic Bulb, Saint Johnswort, Vitamin E Oil
$4.125  each

Unicorn Horn "Standard Supreme" Ear Candles "DIVERS"		Retail $9.50
Supreme ear candles are longer than our regular ear candles so they burn longer. Ear candles can help divers adjust to pressure variations. They come in the white package. Use Standard Herb Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% bleached washed
Waxes: 90% candle wax, 10% beeswax
Herbs: Calendula Flower, Garlic Bulb, Saint Johnswort 
$4.75 each

Unicorn Horn "Herbal Gold" Ear Candles				Retail $9.00 
100% beeswax, 20 times the concentration of herbs as our standard ear candles. These are our most popular and best selling 100% beeswax candles. These are our best, all-around, all-purpose candles. Very good for earaches. They come in the gold package. Use Standard Herb Oil as the pre-candling oil, Garden Delight as post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% bleached washed
Waxes: 100% beeswax
Herbs: Calendula Flower, Garlic Bulb, Saint Johnswort, Vitamin E Oil
$4.50 each
Unicorn Horn Oregon "Wild Lavender Flower" Ear Candles 	Retail $8.50
Good for earaches. Excellent for cleaning ears. They come in the lavender package. Use Unicorn Horn Lavender Herb Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% Bleached Washed
Herbs: Lavender Flower, Ginger, Myrrh, Vitamin E Oil
$4.25 each

Unicorn Horn "Tea Tree Gold" Ear Candles				Retail $9.50
100% beeswax. These are wonderfully strong candles. Superb anti-fungal. Excellent for toning the ear. Very good for infections. They come in the green package. In combination with the Malelueca Bazooka Ear Oil, these candles offer superb dewaxing (ear wax). Anti-fungal properties help in the suppression of ear fungus that can cause itching. Our Candida Vambeata Ear Wash fills out this terrific ear candling combination. It is an excellent anti-fungicide ear wash and is an antiseptic and anti-infective. Kills fungus, germs and disinfects. Excellent to use for and will cure Candida Albicans. Will treat most fungus conditions.
Use Malelueca Bazooka Ear Oil, with its anti-fungal properties, as the pre-candling oil, Garden Delight as the post candling oil and Unicorn Horn Candida Vambeata as the perfect ear wash. This is an unbeatable combination.
Ingredients:
Cotton: 100% bleached washed
Waxes: 100% beeswax
Herbs: Tea Tree Oil, Sage, Clove, Vitamin E Oil
6 sets $4.75 each

Unicorn Horn "Tea Tree Natural" Ear Candles			Retail $9.25
100% beeswax. 100% Natural Muslin Cotton.  These are wonderfully strong candles. Superb anti-fungal. Excellent for toning the ear. Very good for infections. They come in the Golden package. In combination with the Malelueca Bazooka Ear Oil, these candles offer superb dewaxing (ear wax). Anti-fungal properties help in the suppression of ear fungus that can cause itching. Our Candida Vambeata Ear Wash fills out this terrific ear candling combination. It is an excellent anti-fungicide ear wash and is an antiseptic and anti-infective. Kills fungus, germs and disinfects. Excellent to use for and will cure Candida Albicans. Will treat most fungus conditions.
Use Malelueca Bazooka Ear Oil, with its anti-fungal properties, as the pre-candling oil, Garden Delight as the post candling oil and Unicorn Horn Candida Vambeata as the perfect ear wash. This is an unbeatable combination.
Ingredients:
Cotton: 100% Muslin, washed
Waxes: 100% beeswax
Herbs: Tea Tree Oil, Sage, Clove, Vitamin E Oil
$4.625 each

Unicorn Horn "Ginger Stick Supreme" Ear Candles			Retail $10.50
100% beeswax. Soothing and refreshing ear candles. Good all-purpose candles, which smell good. These are delightfully wonderful healing candles. These candles may help headaches and will tone the ears. Recommended, along with Garden Delight Ear Oil, for dirty ear conditions, softening ear wax build up and regular maintenance candling.

Use Garden Delight Ear Oil as the pre-candling oil, Garden Delight Ear Oil as post candling oil and Herbal Magic Wash.

Ingredients:
Cotton: 100% bleached washed
Waxes: 100% beeswax
Herbs: Ginger, Myrrh, Celery Seed Oil, Carrot Seed Oil, Vitamin E Oil
$5.25 each


Unicorn Horn "Garlic Stick" Ear Candles				Retail $16.00
100% beeswax. These are very potent garlic candles. Use Unicorn Horn Garlic Oil as the pre-candling oil, Garden Delight as post candling oil and Herbal Magic Ear Wash.
Ingredients: 
Cotton: 100% bleached washed
Waxes: 100% beeswax
Herbs: Garlic Bulb, Vitamin E Oil
$8.00 each


Unicorn Horn "Sinus Amber" Ear Candles				Retail $9.80
These are very lovely candles, blended 50-50 beeswax and paraffin. They are designed to combat sinus and allergy problems. These are delightful ear candles, smell wonderful and work great. Use Penny Royal Ear Oil as the pre-candling oil, Garden Delight as post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% bleached washed
Waxes: 90% candle wax, 10% beeswax 
Herbs: Penny Royal, Saint Johnswort, Vitamin E Oil
$4.90 each


Unicorn Horn "Orange Citrus" Ear Candles				Retail $9.80
These are 100% essential citrus ear candles, a touch of sunny Florida. Use Garden Delight Ear Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Ingredients:
Cotton: 100% bleached washed
Waxes: 90% candle wax, 10% beeswax
Herbs: Sweet Orange, Lemon, Vitamin E Oil
$4.90 each

Unicorn Horn "Bayberry Golden Myrrh" Ear Candles		Retail $39.00
These are exotic candles. Pure-crude bayberry wax is obtained from the berry of the bayberry shrub. The wax is a coating of the berries and is removed by boiling them in water. This of course takes a lot of berries to make a quantity of wax. Bayberry wax has a melt point of 118-degrees. When put into ear candles you get a very hot flame that burns remarkably well and the length of the burn is extended. Our Bayberry Ear Candles are a mixture of 50% bayberry wax and 50% beeswax, giving them a melt point of 134-degrees. The myrrh oil and the marjoram wild make a perfect healing base of herbs for these truly exotic candles.
Use for earaches. Can be helpful for water on the ear. Good wax softener. Helps with sinus problems. Use Unicorn Horn Myrrh Ear Oil as the pre-candling oil, Garden Delight as post candling oil and Herbal Magic Ear Wash. Recommended to be used by Experianced Candlers Only. 
Ingredients: 
Cotton: 100% bleached washed
Waxs:  50% Bayberry wax, 50% Beeswax 
Herbs: Myrrh, Marjoram Wild, Vitamin E Oil
$19.50 each


Unicorn Horn "Golden Rue" Ear Candles			Retail $29.00
These are exotic candles. 100% beeswax. These are the strongest rue candles in the world. American Indians crushed leaves of rue which they then rolled into a cigarette, the smoke then blown into the ear. This was supposed to be a cure for deafness. A jingle about it was handed down by the Southwestern Indians and sings in translation: "To cure the ear there is nothing like rue. And as a way to say no there is nothing like silence." Use Malelueca Bazooka Ear Oil as the pre-candling oil, Garden Delight as the post candling oil and Herbal Magic Ear Wash.
Pregnant women SHOULD NOT USE these candles or be in the same room a rue candle is being burned. The fumes of rue can cause a miscarriage.
Ingredients:
Cotton: 100% bleached washed
Waxes: 100% beeswax
Herbs: Rue (Ruta Graveolens), Vitamin E Oil
$14.50 each


Unicorn Horn feels it is important for everyone to review the Ear Candling Information Goals Page if you are new to ear candling. Be sure to review Ear Candling - 25 Steps.
We recommend that the oil with the same ingredients as are in the candle be used with that candle as the pre-candling oil. Garden Delight Ear Oil is the post candling oil for all our candles, as it dissolves beeswax residue. All of our candles and oil combinations are designed to be used in three treatments, one set of candles every two weeks for six weeks.

**Comment by pbrooksmc** [comment]
![Uploading River & Flowers & Blueberry Cheesecake August 6, 2019 014.JPG…]()

**Comment by pbrooksmc** [comment]
![River   Flowers   Blueberry Cheesecake August 6, 2019 014](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/0b5a151b-08e8-4fe6-954f-bbee300917ff)

**Comment by zseko** [comment]
Ahoy [pbrooksmc](https://github.com/pbrooksmc),

thank you for your interest in ARRRmada and Pirate Chain. ⚓️

We are currently reviewing your entry and have noticed that you do not yet have a note on your website that you accept ARRR. 

It would be great if this information could be added.

Best RegARRRds 🏴‍☠️

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 001](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/f5a317b7-3e99-4608-9af2-4533ac47df3a)
![Pirate Merchandise 002](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/c22d0587-ce2e-47c9-a1af-4b90b5925fef)
![Pirate Merchandise 003](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/16c5c642-87d0-4f3f-a159-b3fdfc56a1a4)
![Pirate Merchandise 004](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/5ed7fb3e-0f69-4a27-90d7-be81161e4b98)
![Pirate Merchandise 006](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/ba75e4cd-aac5-4380-ad08-b78ec108ccf8)

Tea Shirt $20 Plus shipping Extra Large; Large, Medium and Small

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 007](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/c7c2b53d-f9b5-4be1-8126-2e71ca5faba5)
![Pirate Merchandise 009](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/8d3b09fa-5bfb-4d55-95f0-e153e59c0d22)

Female Pirate Tea-Shirt $25 sizes: Small, Medium and Large

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 012](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/b616759d-ef6f-419e-94fd-81e56336e018)
![Pirate Merchandise 015](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/17e20b40-42a8-4630-ad9a-d35a55ca7bf6)

Cotton Bag $22

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 017](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/f6d56067-c7ef-4a85-a169-4610adbe7637)
![Pirate Merchandise 018](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/336bee6c-78f1-48dc-a450-d7104d79e701)

Sticker $5

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 020](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/17a86042-1d59-452f-9737-fd2cfbb13f48)

Tri Color Sticker $6

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 026](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/59d9cb2b-cda7-46da-977a-f198e265728f)

Cotton multi purpose Knitting, basket weaving, quilting swabs 
$5

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 028](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/3bfbfaea-28a4-46b2-bb46-b6820898b41d)

Buy all three and save $1; $15 total

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 031](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/61f6bfa9-9a29-4d05-afe5-35c0f7fb09cc)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 032](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/d62f592a-dab8-4426-aade-e8fb6b2a8141)

Multi Color Sticker $6

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 033](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/6ca7bde3-b7ec-4691-8532-f6b6431d8c88)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 034](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/507b2468-f5e1-46c6-b26b-94503e69f532)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 035](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/0abb733c-1e56-4fcd-8a7f-0d5f52e2b1a2)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 036](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/32c1fc95-bd2c-4ca5-9c81-beaad445fae8)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 038](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/8b32da03-d6c2-4f94-b437-36020f63d016)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 039](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/1074d8f6-1791-4a4e-a333-8635fa6d6b77)

Book Marks $4, Coaster $15

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 040](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/8441923f-bdd0-4d9b-978e-834b08dd59d2)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 041](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/cf8cd644-8e3a-4a72-a96e-6a71b2140cc5)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 042](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/e07881fc-7b0c-44ff-86f9-28ce69f0fdf6)

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 043](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/5007ee94-7cfa-4a1c-b577-6ca5b8954d59)

Post Card $10

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 049](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/16ad92fd-3b84-4f7c-9098-120c1db0391f)

Post Card and 2 stickers Special $20

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 050](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/c56fc8c4-9499-46da-9855-9f3a3b5e3b72)

Book Marks $4

**Comment by pbrooksmc** [comment]
![Pirate Merchandise 051](https://github.com/ARRRmada/ARRRmada.com/assets/150551991/78f2b2ee-21d8-4888-baa6-6f2b6f454275)

**Comment by pbrooksmc** [comment]
Hi zseko;

Both of the wholesale price lists give everyone that pays with "AAAR" not only wholesale prices but adds an additional 10% discount just for using "ARRR"

Peace & Love from Oregon
Brooks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by pbrooksmc** [comment]
Hi zseko;

The Unicorn Horn open source "Baker" website needs to be updated and I have "ARRR" I am willing to give to anyone who can update the website.

Peace & Love from Oregon
Brooks

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by zseko** [comment]
Ahoy @pbrooksmc,

your entry has been approved.

However, we had to delete your advertisements here on Github, as this is not intended by Github as an independent platform.

To place your ads, we recommend [https://barrrter.com](https://barrrter.com).

Best RegARRRds
zSeko

**Comment by zseko** [comment]
Ahoy @pbrooksmc,

ARRRmada is not a marketplace, but a directory of all merchants that accept ARRR.

I myself am not a contact person for bARRRter. For this you would have to contact **TheQuarterMaster,** who you can find under the following handle on Telegram:
**@TheQuarterMaster**

Or under the handle in the official Pirate Chain Discord channel: **thequartermaster_**
https://piratechain.com/discord

You can also use ARRRmada's Telegram channel to promote your products, that's what it's there for:
https://t.me/+Obq53Fel8bUxMDNh

The ARRRmada Twitter channel will also be posting about your offer shortly.

Best RegARRRds
