### ISSUE TITLE
Private Street

### ISSUE THREAD

**Issue by privatestreet** [ARRRmada/ARRRmada.com#32]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyUDl1NEM0M2klMjIlMkMlMjJQcml2YXRlJTIwU3RyZWV0JTIyJTJDJTIyQSUyMHByZW1pZXJlJTIwZGVzdGluYXRpb24lMjBmb3IlMjBwcml2YWN5LXRoZW1lZCUyMGZhc2hpb24uJTIyJTJDJTIyYWxsLW92ZXItcHJpbnQtcmVjeWNsZWQtdW5pc2V4LWhvb2RpZS13aGl0ZS1iYWNrLTItNjVjM2YxNTYyZWI1Yi5wbmclMjIlMkMlMjJodHRwcyUzQSUyRiUyRnByaXZhdGVzdHJlZXQuc2hvcCUyRiUyMiUyQyU1QiUyMjklMjIlMkMlMjIxMiUyMiU1RCU1RA==
---END CODE---

### Merchant Listing Image

![all-over-print-recycled-unisex-hoodie-white-back-2-65c3f1562eb5b](https://github.com/ARRRmada/ARRRmada.com/assets/159417980/9cffc3f3-9efc-4764-8d9a-bc84f03c60ab)

**Comment by zseko** [comment]
Ahoi @privatestreet,
we are currently checking your submission. Please be patient.

**Comment by zseko** [comment]
Ahoi @privatestreet 

your listing entry has been published.

Welcome to the ARRRmada fleet 🏴‍☠️.

https://twitter.com/PirateARRRmada/status/1756385160415608844
https://t.me/c/1452389363/3611
https://discord.com/channels/512188534111862784/836330876312354836/1205944741234085969

Best RegARRRds
