### ISSUE TITLE
BenBrok.com web design

### ISSUE THREAD

**Issue by Vasco1971** [ARRRmada/ARRRmada.com#34]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIycWJ4akd0YjUlMjIlMkMlMjJCZW5Ccm9rLmNvbSUyMHdlYiUyMGRlc2lnbiUyMiUyQyUyMkFmZm9yZGFibGUlMjB3ZWJzaXRlcyUyMCUyNmFtcCUzQiUyMHdlYiUyMGhvc3RpbmclMjBmb3IlMjBzbWFsbCUyMGJ1c2luZXNzZXMlMjBpbiUyMFBvcnR1Z2FsLiUyMiUyQyUyMmxvZ28yLnBuZyUyMiUyQyUyMmh0dHBzJTNBJTJGJTJGYmVuYnJvay5jb20lMkYlMjIlMkMlNUIlMjI1MSUyMiU1RCU1RA==
---END CODE---

### Merchant Listing Image

![logo2](https://github.com/ARRRmada/ARRRmada.com/assets/51188426/7048714f-2c7f-4601-9bc5-298ff7861f25)

**Comment by ARRRmada** [comment]
@Vasco1971 

Welcome to the ARRRmada.

We are currently checking your entry, but cannot approve it yet because your website is currently unavailable.

**Comment by ARRRmada** [comment]
@Vasco1971 

Your link has been successfully published.

https://twitter.com/PirateARRRmada/status/1771854209974997051
https://t.me/c/1452389363/3624
https://discord.com/channels/512188534111862784/1164569592040013885/1221413137388011590

Best RegARRRds
ARRRmada
