### ISSUE TITLE
LBR designs

### ISSUE THREAD

**Issue by LuukB123** [ARRRmada/ARRRmada.com#38]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyaExCWlYyZ2slMjIlMkMlMjJMQlIlMjBkZXNpZ25zJTIyJTJDJTIyTEJSJTIwZGVzaWducyUyMGlzJTIwYSUyMGZyZWVsYW5jZSUyMGdyYXBoaWMlMjBkZXNpZ25lciUyNiUyM3gyRiUzQmFsbCUyMHJvdW5kJTIwRFRQLWVyJTIwJTVDbmJhc2VkJTIwaW4lMjB0aGUlMjBOZXRoZXJsYW5kcyUyMHJ1biUyMGJ5JTIwTHV1ayUyMEJSb3V3ZXJzLiUyMEhlcmUlMjB0byUyMGhlbHAlMjBwZW9wbGUlMjBpbiUyMGdyYXBoaWMlMjBkZXNpZ24lMjBuZWVkcy4lNUNuJTIyJTJDJTIyTEJSZGVzaWducyUyMGxvZ28ucG5nJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ3d3cubGJyLWRlc2lnbnMubmwlMjIlMkMlNUIlMjIyNiUyMiUyQyUyMjQzJTIyJTJDJTIyNDUlMjIlMkMlMjI1MSUyMiU1RCU1RA==
---END CODE---

### Merchant Listing Image

![LBRdesigns logo](https://github.com/ARRRmada/ARRRmada.com/assets/166825104/911f7188-9ce7-4ded-b1a9-4b30f99039b0)

### Comments for listing reviewer (optional)

LBR designs is a freelance graphic designer/all round DTP-er 
based in the Netherlands run by Luuk BRouwers. Here to help people in there graphic design needs.

**Comment by ARRRmada** [comment]
Welcome to the fleet of Pirate Chain merchants. 🏴‍☠️

Your listing has been approved. ⚓️ 

https://twitter.com/PirateARRRmada/status/1779150848758563037

Best RegARRRds
ARRRmada
