### ISSUE TITLE
Kemah Slingshot Rentals

### ISSUE THREAD

**Issue by Cleverotros** [ARRRmada/ARRRmada.com#4]
---BEGIN CODE---
JTVCJTIydE95NktLUG4lMjIlMkMlMjJLZW1haCUyMFNsaW5nc2hvdCUyMFJlbnRhbHMlMjIlMkMlMjJXZSUyMHJlbnQlMjBzdGFydGluZyUyMGJ5JTIwdGhlJTIwaG91ciUyMCUyNmFtcCUzQiUyMG9mZmVyJTIwaGFsZiUyMGRheSUyQyUyMGZ1bGwlMjBkYXklMjBhcyUyMHdlbGwlMjBhcyUyMG11bHRpJTIwZGF5JTIwb3B0aW9ucy4lMjBXZSUyMGFyZSUyMGElMjBsb2NhbGx5JTIwZmFtaWx5JTIwb3duZWQlMjBhbmQlMjBvcGVyYXRlZCUyMGJ1c2luZXNzLiUyMiUyQyUyMkE3OUI5OEUxLTZCM0ItNEFFOC04NjY0LUNGMDQ4MDY0QjQ0MC5qcGVnJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ3d3cua2VtYWhzbGluZ3Nob3RyZW50YWxzLmNvbSUyRiUyMiUyQyU1QiUyMjUlMjIlMkMlMjI1NiUyMiUyQyUyMjMxJTIyJTJDJTIyMzUlMjIlMkMlMjI0NSUyMiUyQyUyMjUwJTIyJTVEJTVE
---END CODE---

**Comment by ARRRmada** [comment]
added
