### ISSUE TITLE
Blue Dragon Consulting

### ISSUE THREAD

**Issue by bluedragonconsulting** [ARRRmada/ARRRmada.com#40]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIycGVCNDhYelYlMjIlMkMlMjJCbHVlJTIwRHJhZ29uJTIwQ29uc3VsdGluZyUyMiUyQyUyMllvdXIlMjB0cnVzdGVkJTIwcGFydG5lciUyMGZvciUyMHNlYW1sZXNzJTIwYnVzaW5lc3MlMjBpbnRlZ3JhdGlvbiUyMGluJTIwSW5kb25lc2lhJTJDJTIwd2l0aCUyMGElMjBwYXJ0aWN1bGFyJTIwZW1waGFzaXMlMjBvbiUyMGJ1c2luZXNzJTIwcmVsb2NhdGlvbiUyMGFuZCUyMGNyeXB0b2N1cnJlbmN5JTIwc3RyYXRlZ2llcy4lMjIlMkMlMjJCbHVlX0RyYWdvbl9Mb2dvMC5wbmclMjIlMkMlMjJodHRwcyUzQSUyRiUyRmJsdWVkcmFnb24uY29uc3VsdGluZyUyRmJ1c2luZXNzJTJGJTIyJTJDJTVCJTIyNTclMjIlMkMlMjIxMiUyMiU1RCU1RA==
---END CODE---

### Merchant Listing Image

![Blue_Dragon_Logo0](https://github.com/ARRRmada/ARRRmada.com/assets/171893673/ce078163-fb44-4f08-b44b-2d9a14b608c8)

**Comment by ARRRmada** [comment]
Welcome to the fleet of Pirate Chain merchants. 🏴‍☠️

Your listing has been approved. ⚓️

https://x.com/PirateARRRmada/status/1808505177931985201
https://t.me/c/1452389363/3663

Best RegARRRds
ARRRmada
