### ISSUE TITLE
Essential Oil Wizardry

### ISSUE THREAD

**Issue by DOCTANICK** [ARRRmada/ARRRmada.com#41]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyRmdXSGxlaXMlMjIlMkMlMjJFc3NlbnRpYWwlMjBPaWwlMjBXaXphcmRyeSUyMiUyQyUyMlRoZSUyMGZpbmVzdCUyMHF1YWxpdHklMjBvcmdhbmljJTIwJTI2JTIzeDJGJTNCJTIwd2lsZCUyMGNyYWZ0ZWQlMjBFc3NlbnRpYWwlMjBPaWxzJTJDJTIwV2l6YXJkJTIwQWxjaGVteSUyMEJsZW5kcyUyQyUyMENlcmVtb25pYWwlMjBhbmQlMjBUaGVyYXBldXRpYyUyME9pbHMlMkMlMjBVbHRyYXNvbmljJTIwVGluY3R1cmVzJTIwJTI2YW1wJTNCJTIwQm90YW5pY2FsJTIwUGVyZnVtZXMuJTIyJTJDJTIySU1HXzIwMjQwNjA2XzEwMjQ0MF85MjQucG5nJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ3d3cuZXNzZW50aWFsb2lsd2l6YXJkcnkuY29tJTIyJTJDJTVCJTIyMjclMjIlMkMlMjIzMiUyMiUyQyUyMjM1JTIyJTJDJTIyNDYlMjIlNUQlNUQ=
---END CODE---

### Merchant Listing Image

![IMG_20240606_102440_924](https://github.com/ARRRmada/ARRRmada.com/assets/171969018/05e5bac1-b791-4056-a4fb-3af235b10d1d)

**Comment by DOCTANICK** [comment]
Thanks so much!

**Comment by ARRRmada** [comment]
Ahoi @DOCTANICK

thank you for being on board. ⚓️

Your listing has been approved and shared on the following platforms.

https://x.com/PirateARRRmada/status/1808511293386604610
https://t.me/c/1452389363/3664

Best RegARRRds 🏴‍☠️

**Comment by DOCTANICK** [comment]
thank you much for your assistance with this!
