### ISSUE TITLE
Teebs

### ISSUE THREAD

**Issue by Teebs-the-Defiant** [ARRRmada/ARRRmada.com#44]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyQWtTbEdEbUMlMjIlMkMlMjJUZWVicyUyMiUyQyUyMlByb2R1Y2VyJTJDJTIwVmlkZW8lMjBFZGl0b3IlMkMlMjBhbmQlMjBHcmFwaGljJTIwRGVzaWduZXIlMjIlMkMlMjJUZWVicyUyMFBpYyUyMDIucG5nJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ0ZWVicy5teXBvcnRmb2xpby5jb20lMkYlMjIlMkMlNUIlMjI1NiUyMiUyQyUyMjI2JTIyJTJDJTIyNDUlMjIlNUQlNUQ=
---END CODE---

### Merchant Listing Image

![Teebs Pic 2](https://github.com/user-attachments/assets/3368e047-53f1-435b-afa1-f6a2b4822869)

### Comments for listing reviewer (optional)

About me:

Ahoy! I'm Teebs, a passionate Freelance Producer, Video Editor, and Graphic Designer with a talent for crafting engaging content across a wide range of formats. From long-form videos to punchy YouTube Shorts, I love finding creative ways to bring ideas to life. Whether it's attention-grabbing commercials, clever meme videos, AI-enhanced visuals, or music videos that vibe, I’m all about pushing boundaries in storytelling and digital media.

With experience editing for the "Daily Dose of Pirate Chain" and currently serving as the Producer & Lead Video Editor for The Crypto Vigilante newsletter since November 2022, I bring a unique skill set and a strong work ethic to every project.

Be sure to check out my video editing showcase portfolio at https://teebs.myportfolio.com/ to view examples of some of my past and recent work. My rate is typically $30 per hour, but I am flexible and open to price negotiation.

Contact me if you have a project in need of video editing services and let's make your vision a reality!

Services:

Customized graphic design and video editing services that fit your needs. From long form videos to YouTube Shorts, commercials, memes, gifs, thumbnails, music videos, teaser trailers, AI artworks, and more!

Links / Contact:

Showcase Portfolio: https://teebs.myportfolio.com/

Follow me on Twitter/X: @Captn_Teebs

Telegram: @Teebs_the_Defiant

Discord: teebs7171

Keybase: captn_teebs

Signal: Teebs.18

**Comment by zseko** [comment]
Welcome to the ARRRmada and thanks for submitting the listing! We are reviewing your submission now.

**Comment by ARRRmada** [comment]
Thx for joining ARRRmada.
